/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 7acb950233301359768cf1c7242e673f)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	APP_URL: string;
	INBOUND_DOMAIN: string;
	INBOUND_ADDRESS_STYLE: string;
	INBOUND_PLUS_USER: string;
	MAIL_FROM: string;
	MAILER: string;
	SIGNUPS: string;
	ALLOWED_EMAILS: string;
	WITNESS_JUDGE: string;
	WITNESS_MODEL: string;
	WITNESS_MASTER_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_URL" | "INBOUND_DOMAIN" | "INBOUND_ADDRESS_STYLE" | "INBOUND_PLUS_USER" | "MAIL_FROM" | "MAILER" | "SIGNUPS" | "ALLOWED_EMAILS" | "WITNESS_JUDGE" | "WITNESS_MODEL" | "WITNESS_MASTER_KEY">> {}
}
